CREATE TABLE responsible (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   full_name VARCHAR(255),
   cpf VARCHAR(255),
   date_birth TIMESTAMP WITHOUT TIME ZONE,
   nationality VARCHAR(255),
   gender VARCHAR(255),
   email VARCHAR(255),
   bond VARCHAR(255),
   CONSTRAINT pk_responsible PRIMARY KEY (id)
);

CREATE TABLE account (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   user_name VARCHAR(255),
   password VARCHAR(255),
   active BOOLEAN,
   responsible_id BIGINT,
   CONSTRAINT pk_account PRIMARY KEY (id),
   CONSTRAINT FK_ACCOUNT_ON_RESPONSIBLE
       FOREIGN KEY (responsible_id) REFERENCES responsible (id)
);

CREATE TABLE responsible_adress (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   cep VARCHAR(255),
   public_place VARCHAR(255),
   number VARCHAR(255),
   neighborhood VARCHAR(255),
   complement VARCHAR(255),
   reference_point VARCHAR(255),
   state VARCHAR(255),
   city VARCHAR(255),
   responsible_id BIGINT,
   CONSTRAINT pk_responsibleadress PRIMARY KEY (id),
   CONSTRAINT FK_RESPONSIBLEADRESS_ON_RESPONSIBLE
       FOREIGN KEY (responsible_id) REFERENCES responsible (id)
);

CREATE TABLE dependent (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   full_name VARCHAR(255),
   cpf VARCHAR(255),
   date_birth TIMESTAMP WITHOUT TIME ZONE,
   nationality VARCHAR(255),
   gender VARCHAR(255),
   support_level_tea VARCHAR(255),
   medical_report VARCHAR(255),
   responsible_id BIGINT,
   CONSTRAINT pk_dependent PRIMARY KEY (id),
   CONSTRAINT FK_DEPENDENT_ON_RESPONSIBLE
        FOREIGN KEY (responsible_id) REFERENCES responsible (id)
);

